version: 2
jobs:
  build:
    docker:
      - image: aeternas/swadeshness-couperose:$CIRCLE_BRANCH
    branches:
      only:
        - master
        - development
    working_directory: /home/circleci/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run: java -jar couperose-0.1.0-SNAPSHOT-standalone.jar
