version: 2
jobs:
  build:
    docker:
      - image: aeternas/swadeshness-couperose:$CIRCLE_BRANCH
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - deploy: java -jar couperose-0.1.0-SNAPSHOT-standalone.jar
