aliases:
  - &docker_image
    - image: aeternas/swadeshness-couperose:$CIRCLE_BRANCH
  - &run_command: java -jar couperose-0.1.0-SNAPSHOT-standalone.jar
version: 2.1
jobs:
  build:
    docker: *docker_image
    working_directory: /home/circleci/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run: *run_command
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

